#mapply()
mean.x = apply(X, 2, mean)
sd.x = apply(X, 2, sd)
head(cbind(mean.x, sd.x),5)
tail(cbind(mean.x, sd.x),5)
windows(height=5, width=6)
plot(mean.x, main="Trend of Mean")
windows(height=5, width=6)
plot(sd.x, main="Trend of SD")
